name: CI

on:
  push:
    branches:
      - try/gh-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.3
      with:
        hugo-version: '0.58.3'
    - name: Build
      run: hugo --minify
