name: CI

on:
  push:
    branches:
      - content

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.3
      with:
        hugo-version: 'latest'
    - name: Build site
      run: hugo --gc --minify --cleanDestinationDir
    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
